name: Upstream

on:
  schedule:
    - cron: "0 1 * * *"
  push:
  pull_request:

jobs:
  build:
    runs-on: "ubuntu-latest"
    # if: "contains(github.event.head_commit.message, 'test-upstream') || (github.repository == 'dask/dask' && github.event_name != 'pull_request')"

    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Setup Conda Environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          miniconda-version: "latest"
          python-version: 3.8
          environment-file: continuous_integration/environment-3.8-dev.yaml
          activate-environment: test-environment
          auto-activate-base: false

      - name: Install
        shell: bash -l {0}
        env:
          UPSTREAM_DEV: 1
        run: source continuous_integration/scripts/install.sh

      - name: Run tests
        shell: bash -l {0}
        run: source continuous_integration/scripts/run_tests.sh
